version: 2
updates:
- package-ecosystem: terraform
  directory: "/"
  open-pull-requests-limit: 10
  schedule:
    interval: daily
  reviewers:
    - dotboris

- package-ecosystem: github-actions
  directory: "/"
  open-pull-requests-limit: 10
  schedule:
    interval: daily
  reviewers:
    - dotboris
